#!/usr/bin/env python3
"""Converts an EPUB into DODO's Book JSON (src/data/mockBooks.ts shape), for
testing the app on a real, full-length book.

Keeps numbered chapters and appendices; skips front matter, part dividers and
the index. Inside chapters it keeps prose (paragraphs, list items, headings)
and drops what can't be read aloud: code listings, tables, images, figure
captions and code annotations.

Usage: python3 scripts/epub_to_book.py path/to/Book.epub [more.epub ...]

Each book is written to src/data/generated/<book-id>.json, and
src/data/generated/index.ts is rebuilt to list every book there, so the app's
library shows all of them (plus the sample books). The folder is git-ignored.
"""
import html.parser
import glob
import json
import os
import posixpath
import re
import sys
import zipfile

BLOCKS = {'p', 'li', 'h1', 'h2', 'h3', 'h4'}
SKIP_TAGS = {'pre', 'table', 'img', 'script', 'style'}
SKIP_CLASSES = {'fm-code-annotation', 'figure1', 'annotation'}
CHAPTER_TITLE = re.compile(r'^(\d+\s|Appendix\b)')


class ChapterParser(html.parser.HTMLParser):
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.title = ''
        self.paragraphs = []
        self._skip = 0  # depth inside skipped elements
        self._block = None  # text of the block being read
        self._in_h1 = False
        self._void = {'img', 'br', 'hr', 'col'}

    def _flush(self):
        if self._block is not None:
            text = ' '.join(''.join(self._block).split())
            if text:
                self.paragraphs.append(text)
        self._block = None

    def handle_starttag(self, tag, attrs):
        classes = set((dict(attrs).get('class') or '').split())
        if self._skip:
            if tag not in self._void:
                self._skip += 1
            return
        if tag in SKIP_TAGS or classes & SKIP_CLASSES:
            if tag not in self._void:
                self._flush()
                self._skip = 1
            return
        if tag in BLOCKS:
            self._flush()
            self._block = []
            self._in_h1 = tag == 'h1'

    def handle_endtag(self, tag):
        if self._skip:
            self._skip -= 1
            return
        if tag in BLOCKS:
            if self._in_h1 and self._block is not None:
                self.title = ' '.join(''.join(self._block).split())
                self._block = None
                self._in_h1 = False
                return
            self._flush()

    def handle_data(self, data):
        if not self._skip and self._block is not None:
            self._block.append(data)


def convert(epub_path, out_dir):
    z = zipfile.ZipFile(epub_path)
    container = z.read('META-INF/container.xml').decode()
    opf_path = re.search(r'full-path="([^"]+)"', container).group(1)
    opf = z.read(opf_path).decode()
    base = posixpath.dirname(opf_path)

    items = {}
    for item in re.findall(r'<item\b[^>]*>', opf):
        item_id = re.search(r'\bid="([^"]+)"', item)
        href = re.search(r'\bhref="([^"]+)"', item)
        if item_id and href:
            items[item_id.group(1)] = posixpath.normpath(posixpath.join(base, href.group(1)))
    spine = re.findall(r'<itemref\b[^>]*\bidref="([^"]+)"', opf)

    def meta(tag):
        m = re.search(rf'<dc:{tag}[^>]*>([^<]*)', opf)
        return html.unescape(m.group(1)).strip() if m else ''

    title, author = meta('title'), meta('creator')
    chapters, idx, paragraph_idx = [], 0, 0
    for idref in spine:
        parser = ChapterParser()
        parser.feed(z.read(items[idref]).decode('utf-8', 'ignore'))
        if not CHAPTER_TITLE.match(parser.title) or not parser.paragraphs:
            continue
        paragraphs = []
        for text in parser.paragraphs:
            words = [{'text': w, 'idx': idx + i} for i, w in enumerate(text.split())]
            idx += len(words)
            paragraphs.append({'paragraphIdx': paragraph_idx, 'words': words})
            paragraph_idx += 1
        chapters.append({'chapterIdx': len(chapters), 'title': parser.title, 'paragraphs': paragraphs})
        print(f'{parser.title[:50]:50} {sum(len(p["words"]) for p in paragraphs):7} words')

    book = {
        'id': re.sub(r'[^a-z0-9]+', '-', title.lower()).strip('-'),
        'title': title,
        'author': author,
        'coverColor': '#2B4B6F',
        'progress': 0,
        'chapters': chapters,
    }
    out_path = os.path.join(out_dir, f"{book['id']}.json")
    with open(out_path, 'w') as f:
        json.dump(book, f, ensure_ascii=False, separators=(',', ':'))
    print(f'{title} by {author}: {len(chapters)} chapters, {paragraph_idx} paragraphs, {idx} words -> {out_path}')


def write_index(out_dir):
    names = sorted(os.path.basename(p) for p in glob.glob(os.path.join(out_dir, '*.json')))
    lines = [
        '// Generated by scripts/epub_to_book.py. Do not edit.',
        "import type { Book } from '../mockBooks';",
        '',
        'export const generatedBooks: Book[] = [',
        *[f"  require('./{name}') as Book," for name in names],
        '];',
        '',
    ]
    with open(os.path.join(out_dir, 'index.ts'), 'w') as f:
        f.write('\n'.join(lines))
    print(f'Library: {len(names)} converted book(s) in {out_dir}')


if __name__ == '__main__':
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    out_dir = os.path.join(os.path.dirname(__file__), '..', 'src', 'data', 'generated')
    os.makedirs(out_dir, exist_ok=True)
    for epub in sys.argv[1:]:
        convert(epub, out_dir)
    write_index(out_dir)
